### PR TITLE
error refactor

### PR DESCRIPTION
**Pull request by mbroadst**
open for discussion about different implementation methods

### CODE REVIEW

**Comment by Rush** [comment]
I really like you're cleanup. What's missing is a custom error class `LibvirtError`. When catching errors it's important to be able to do:
```js
.catch(LibvirtError, err => {
  console.log('This is error from libvirt and thus we can access its custom stuff', err.code
});
```

Sadly, I don't know how to make a custom `Error` class in v8 code :-( Maybe it's as simple as ordinary object with `Error` set to its prototype but there may be some subtle details which make stacktraces work properly.

**Comment by mbroadst** [comment]
@Rush ah yeah! let me see if I can sort that business out

**Comment by mbroadst** [comment]
@Rush bummer looks like that's not going to be possible (see: https://github.com/nodejs/nan/issues/586). I'd say we should still take two lessons from this PR over into yours:

1) simplifying the error creation to a single static method that just returns an object (in fact, we could still theoretically keep it as an `Error` object, and trap for those in the javascript side?)

2) I would prefer to keep something like the `NLV_ERROR` macro, so that we are only wrapping the creation of an error to add the contextual data. Making macros that mask throwing, or the call site of the error being managed I think reduces readability.

Thoughts?

**Comment by Rush** [comment]
Pity, but I think we can just add that JS layer to create `LibvirtError` instances from your `Error` instances and all will be good. https://github.com/hooklift/node-libvirt/pull/71/files#diff-6d186b954a58d5bb740f73d84fe39073R14

**Comment by mbroadst** [comment]
@Rush yeah, I was sort of suggesting we just merge the interesting bits of my implementation here directly into yours (keeping attribution for the fact that you did the real work here!).

There is actually one more tricky solution we could use in that bluebird differentiates between general errors and operational errors. This allows you to do: `promise.error(err => ... )` (rather than `.catch`) and pass through things like Syntax and Type errors (errors which are more likely to be errors introduced by the developer). It does this by looking for a `isOperational` property on the error object, so we could do that as well but it ties us to bluebird so I'm not sure its the best way to go, especially with the recent discussions in node-land about supporting global replacement of the "promise backend".

**Pull request closed without merging**
