### PR TITLE
initial import of async refactor

### PR DESCRIPTION
**Pull request by mbroadst**
This is the initial import of the async refactor I picked up from @atoy40 's work. There are a few outstanding issues:

  * test don't run cleanly because there are myriad issues with tracking state with the test driver
  * some methods were not converted to be asynchronous (they are left in a unfinished sync state)
  * potential for many more refactorings to reduce code duplication

This is intended to be a starting point to continue the work, but I'm running out of time locally. Hopefully others can help pick up on this work, and at least test with their existing code to identify issues

### CODE REVIEW

**Comment by mbroadst** [comment]
@atoy40 @c4milo @Rush please give it a whirl when you have a second, hopefully figuring out issues with existing code should be a fairly quick process.

**Comment by mbroadst** [comment]
fyi, you should be able to test this branch out by replacing your dependency reference to node-libvirt in your package.json to:

```
   "libvirt": "hooklift/node-libvirt#async-refactor",
```

**Comment by c4milo** [comment]
@mbroadst thanks for all the hard work again. I will test the branch as soon as I can.

**Comment by atoy40** [comment]
hello,
it looks really good :) i'll try it asap. Did you removed the event implementation in this branch ?

Anthony.

**Comment by mbroadst** [comment]
@atoy40 no I actually added back everything I initially removed and left those synchronous. You should still be able to use those methods, just remember that they are synchronous when composing them for the time being. Hopefully I can garner some help converting those to be asynchronous as well :smiling_imp:

**Comment by mbroadst** [comment]
@atoy40 ah! sorry I thought you meant the Domain Events.. yeah I did remove the Event implementation, I couldn't tell what was actually using it. That can easily be added back

**Comment by atoy40** [comment]
Ok, Did you move stuffs coded in event_impl.cc/h ?
Also, may be it can help : I just pushed my finished domain object and mocha tests in my fork/async branch.

Anthony.

**Comment by Rush** [comment]
Would be cool to have those sync methods but I think they should print a big fat WARNING. This way porting code would be much easier and you would still know that there is stuff to fix.

**Comment by atoy40** [comment]
Oh, ok, juste seen you second message :)
Yes the event impl (event_impl.h/cc) is very important. Libvirt itself doesn't implement the event handling, it only provide a mechanism to register event/callback, but not how event are propagate. The implementation use libuv to check file descriptor and propagate event when they occurs.

The SetupEvent() method (setupEventy() on javascript side) call the libvirt virEventRegisterImpl function.

Without calling libvirt.setupEvent(), you can register as many event as you like... they'll never be call :)

**Comment by mbroadst** [comment]
@atoy40 whoops, yeah just read through and realized that! Okay I've added it back in :)

**Comment by mbroadst** [comment]
@Rush the sync methods are definitely back in, and they are marked as being incomplete in the source code. Frankly, I think it would be desirable to not merge any of this work into master until every last bit is asynchronous. I'll go ahead now and fprintf(stderr, ..) that it's unfinished sync for now

**Comment by mbroadst** [comment]
@atoy40 yeah I think your work can help as well, maybe you would be willing to rebase on the async-refactor branch and put together a PR to complete the rest of the Domain implementation? With the mocha tests as well. 

@Rush I've just pushed commits to print on the command line when a synchronous method is being used. 

For both of you (and anyone else lurking): I'm going to be actively monitoring this conversation, and issues related to async refactoring. I will take any pull requests into consideration, and am definitely interested in hearing feedback to catch any bugs I've missed. My main goal here is essentially to crowdsource the completion of this :smile:

**Comment by atoy40** [comment]
Ok, I think I'll find an hour or two this afternoon to implement "not-yet-async" method in domain.

Another comment, in some domain methods/workers, you've decided to pass a boolean "true" to the 2nd argument of the callback, as it was coded in the sync version. I think we've to removed these booleans. If the operation failed ... err is given to the callback, if it succeed ... no needs to check a boolean :)

**Comment by mbroadst** [comment]
@atoy40 I think any place I still return NanTrue()/NanFalse() is in the unfinished sync methods. Generally I've converted these to NanReturnUndefined or NanNull for the other callback argument. Can you point to a place in the code where you think I've done this incorrectly?

**Comment by atoy40** [comment]
For example, in the execute methods for AttachDevice and UpdateDevice, you set data_ to true... and these workers are PrimitiveReturnWorker<bool>. IMHO, this boolean isn't helpful. In general all "set" accessors don't need it, they only have to return "error" to the callback.

**Comment by atoy40** [comment]
Just a reminder here : there is some char* returned by libvirt to free, at least in the domain object. Any char* allocate by libvirt as to be freed, except (at least...) for the virDomainGetName because this one is managed by libvirt itself.

**Comment by mbroadst** [comment]
@atoy40 yeah I tried to be careful to free char* 's when they were returned vs the const char*'s which don't need to be managed. Did you find an example where I screwed up?

As for the returning the booleans, I'm a bit conflicted. Following node's standard callback approach => (err, result) allows really easy promisification so I was thinking you could just ignore the returned boolean. I'm on the fence about it, if you submit a PR to remove it I'm not actively against it :smile:

**Comment by atoy40** [comment]
As you said the booleans can be ignored :)
I'm adding missing domain method right now ... bad memories come back !!!! :s
for the char* ... for example in GetOSType, it as to be freed according to http://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetOSType

**Comment by mbroadst** [comment]
@atoy40 oh yeah whoops, wonder why the compiler didn't catch me assigning the char* to const char*

**Comment by atoy40** [comment]
@mbroadst , i think you've done mistakes in argument checkings
to take an example among others, the Domain::GetBlockStats :+1: 
```
  if (args.Length() != 2 &&
      (!args[0]->IsString() && !args[1]->IsFunction())) {
    NanThrowTypeError("You must specify a path and callback");
    NanReturnUndefined();
  }
```

if you have two args : an integer and a function then you didn't catch the error.

**Comment by mbroadst** [comment]
@atoy40 looks like my logic was a little flipped :smile:, should be || for the second check. Are you going to update that in your PRs, or should I get on it?

**Comment by atoy40** [comment]
@mbroadst , yes I can check/correct it, at least in domain.cc (i'm finishing it this afternoon). I think we can replace all && to || => bad arg count OR bad arg(0) type OR .... means error.

**Comment by atoy40** [comment]
@mbroadst @c4milo , i'm starting a JS shim for promisification of the async library.
For the Hypervisor class ... no worries , as the constructor is exposed, a simple call to Promise.promisifyAll(libvirt.Hypervisor.prototype); do the job.
But others classes are not exposed, so, we've (imho...) two choices :
- We can expose constructors of Domain, Storage, etc... (even if there is no reason to instanciate it directly) to simplify the process.
- We can, in the JS shim, rewrite function that return these objects (essentially lookup* function) to promise created instances on-the-fly.

what do you thing about ?

**Comment by mbroadst** [comment]
@atoy40 I'm not sure you need to do that, can't you just do ```bluebird.promisifyAll(Domain.prototype);``` ?

**Comment by atoy40** [comment]
@mbroadst Sure ... this is solution one. But what is Domain ? : a function to instantiate domain.
And as-is, this function is not exposed ... so libvirt.Domain is undefined on the javascript side.
The only constructor function exposed is Hypervisor. and this is correct, because all other object come from an hypervisor method
If we want to get libvirt.Domain, we've to expose constructor function (even if there is no other usage than primifying). These two lines to that for hypervisor :
```
NanAssignPersistent(constructor, t->GetFunction());
exports->Set(NanNew("Hypervisor"), t->GetFunction());
```

**Comment by mbroadst** [comment]
@atoy40 ah yeah, I see the problem now. Hmm, I say we expose all constructors but disallow explicit creation by users.

**Comment by atoy40** [comment]
@mbroadst 
just adding
```c++
exports->Set(NanNew("Domain"), t->GetFunction());
```
to the Domain Initialize function works perfect.

Here a simple example
```javascript
var join = require("bluebird").join;
var libvirt = require("./lib/index.js");
var hv = libvirt.createHypervisor("qemu:///system");

hv.connectAsync()
.then(function() {
  return hv.listDefinedDomainsAsync();
})
.map(function(name) {
  return hv.lookupDomainByNameAsync(name);
})
.map(function(domain) {
  return join(
    domain.getUUIDAsync(),
    domain.getInfoAsync()
  );
})
.each(function(res) {
  console.log("uuid:  " + res[0]);
  console.log("vcpus: " + res[1].vcpus);
})
.catch(function(err) {
  console.log("error : "+err);
});
```

and the console result : 

```
uuid:  74beca07-0828-0313-37bd-aead4e960481
vcpus: 1
uuid:  13ce1427-4254-e6b7-3829-23054418d289
vcpus: 2
uuid:  10f5f251-8827-b8b4-c848-2f80be33c957
vcpus: 1
```

**Comment by mbroadst** [comment]
@atoy40 awesome :smile:. I guess what I was getting as is that you can now actually create the object right? I believe if you add a "New" method, and check if its a ContructCall and block that we can emit warnings if someone tries to do:

```
var virt = require('libvirt');
var test = new virt.Domain();
```

right?

**Comment by mbroadst** [comment]
@atoy40 also fwiw there are some other really cool bluebird features to play around with, like spread:

```
var libvirt = require("./lib/index.js");
var hv = libvirt.createHypervisor("qemu:///system");

hv.connectAsync()
  .then(function() {
    return hv.listDefinedDomainsAsync();
  })
  .map(function(name) {
    return hv.lookupDomainByNameAsync(name);
  })
  .map(function(domain) {
    return Promise.all([
      domain.getUUIDAsync(),
      domain.getInfoAsync()
    ]);
  })
  .spread(function(uuid, info) {
    console.log("uuid:  " + uuid);
    console.log("vcpus: " + info);
  })
  .catch(function(err) {
    console.log("error : " + err);
  });
```

**Comment by atoy40** [comment]
No, you didn't need to create New function...
it's javascript ...... strange thing :D
if you "console.log" libvirt.Domain .... you get undefined .... because no c++ function is associate to constructor ... but you can still access libvirt.Domain.prototype ... exactly what we need :)
in other words, the accessor libvirt.Domain return undefined, but libvirt.Domain exists !

**Comment by atoy40** [comment]
@mbroadst yes, i'm new to the promise world yet :) tips and good practices are welcome !

**Comment by mbroadst** [comment]
@atoy40 awesome :smile:

**Comment by mbroadst** [comment]
@atoy40 another thought I was playing around with was making everything async by default, versus wrapping with bluebird. Ideally connect would just be async instead of having connect and connectAsync, so that we just straight up force people into promise mode. The idea would be to use like [node-bindings](https://github.com/TooTallNate/node-bindings) and have a /lib javascript for every class and to return objects that had async calls to the original callback form but without "Async" in the name. This would also allow us to e.g. easily add methods to return JSON along side methods that return XML (getCapabilitiesJson?) Anyway, just an idea!

**Comment by atoy40** [comment]
yes, and add more useful method, for example have a .getDomains which can get Defined and Running domains in a common form

**Comment by mbroadst** [comment]
@atoy40 do you have a PR for adding those exports? I'd like to use the promisifed version of the library in my current code if possible.

**Comment by atoy40** [comment]
@mbroadst I'll PR it today.

**Comment by atoy40** [comment]
@mbroadst @c4milo I've a really strange "bug" with libvirt events. I've an application which :
- connect to hypervisor then :
-- start a setInterval every second to get/graph cpu and network interface of each started domains
-- register a lifecycle event on any domain

My program works well, but after some variable time (from seconds to some minutes) i get a node assertion (and a SIGABRT signal):
nodejs: ../deps/uv/src/unix/linux-core.c:157: uv__io_poll: Assertion `w->pevents != 0' failed.
or (but less often)
nodejs: ../deps/uv/src/unix/linux-core.c:159: uv__io_poll: Assertion `w->fd < (int) loop->nwatchers' failed.

This happen as soon as I've the interval started AND libvirt.startEventLoop() called
With only libvirt event registration : works fine
with only a setInterval : works fine
(at least for the hour or two i've tested...)

It never happened with the old synchronous code (but the event_impl code by itself is unchanged ... only starting/stopping uv_poll and uv_timer)

Any idea guys ?

**Comment by mbroadst** [comment]
@atoy40 can you isolate it to a simple test case? I would guess that maybe a few things could be happening:

   * you are inadvertently creating too many listeners on the EventEmitter
   * you are inadvertently creating too many listeners from the C++ side by registering events
   * the event_impl needs to be improved (I haven't looked at this at all, so I'm guessing there is stuff to clean up in there)

An easy check probably would be to print out the result of your call to registerEvent, it will return a callback ID for the callback registered to listen for the event. If that number is increasing like crazy I think you'll have found your issue

**Comment by atoy40** [comment]
@mbroadst I use the actual async-refactor branch (no EventEmmiter), and i'm only registering one event (so it get ID 0), as for the setInterval which his only started once.

**Comment by mbroadst** [comment]
@atoy40 it might be worth uncommenting all the commented out fprintf lines in event_impl.cc to see if there's not something fishy going on there

**Comment by atoy40** [comment]
@mbroadst @c4milo I think I found the problem.
It comes from the fact libvirt launch a thread to call our EventImpl::UpdateHandle function. So i was modifying uv_poll and uv_timer from a thread which is not the one running the uv loop... so sometimes ... collisions happened...
I modified the behavior so:
- Now, in EventImpl::UpdateHandle (call by libvirt), I just save the requested modification and don't touch polls and timers anymore.
- Use of a uv_check (a function call once per loop iteration, so in the "node" thread) to really apply modification to polls and timers
- use a mutex to synchronize uv loop and libvirt

I'll PR it after some more tests and cleaning.

**Comment by mbroadst** [comment]
@atoy40 yeah the event implementation is definitely a very unsafe code path, this was part of my intent with with the EventEmitters (the existing callback method breaks a lot of contracts v8 works very hard to enforce).

By the way, I was going to merge that today into the async-refactor branch unless you have strong objections? I know that it doesn't currently support listening to events from all domains, but I can work on a solution for that once we get the ball rolling and get the code in.

**Comment by atoy40** [comment]
@mbroadst Yes, but using EventEmmiter or callback doesn't change the fact you've to implement functions required by virEventRegisterImpl() to link it to the UV loop
No problem to merge, I'll adapt my code, but may be you can remove you modifications in events_impl.[c|h], because i've redsigned it to fix the thread issue. And I can confirm, it works perfect now as shown in this screenshot ! :) :
http://depot.univ-pau.fr/files/7_days/2015422_1429700867GIs3fC/capture_du_20150422_130647.png

**Comment by mbroadst** [comment]
@atoy40 awesome! :smile: 

The changes that I have in event_imply on that PR were required for dealing with disparate versions of libuv. Ubuntu currently ships with libuv0 by default, while on my mac I've got libuv1. Other than that, your code should apply cleanly on top of that right? (I assume you didn't incorporate that change)

**Comment by atoy40** [comment]
@mbroadst I incorporate the changes you've made, but it'll probably merge without problem ..
I created a PR : https://github.com/hooklift/node-libvirt/pull/46

**Comment by mbroadst** [comment]
@atoy40 sounds good, I'll just rebase my PR once we merge #46

**Comment by mbroadst** [comment]
@atoy40 is that dashboard open source? I'd love to play around with it!

**Comment by atoy40** [comment]
@mbroadst not yet, just an application i'm developing here at works.

**Pull request merged**
